version = 1

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true

[[transformers]]
name = "prettier"
enabled = true