
name: stage CI/CD

on:
  push:
    branches: [stage]
  pull_request:
    branches: [stage]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Super-Linter
        uses: github/super-linter@v4.8.4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: staging

      - run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run the tests
        run: npm test -- --coverage

   
  